<a href="https://colab.research.google.com/github/sabavathvijay/AUDIO-TRANSCRIPTION-APP/blob/main/Vijay_05H7_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
pip install numpy

In [4]:
import numpy as np

**1.Even Odd  numbers in array**


In [5]:
arr=np.arange(1,11)

In [6]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
even=arr[arr%2==0]
odd=arr[arr%2!=0]

In [8]:
print("These are  Even numbers in array are: ",even)
print("These are  Odd numbers in array are: ",odd)
print('DONE ...')

These are  Even numbers in array are:  [ 2  4  6  8 10]
These are  Odd numbers in array are:  [1 3 5 7 9]
DONE ...


**2. Prime numbers in Array**

In [9]:
import random


In [10]:
'''
arr1=[]
for i in range(20):
  arr1.append(random.randint(1,20))
'''
arr1=np.arange(1,30)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [11]:
def IsPrime(x):
  if  x<2:
    return False
  count=0
  for i in range(2 ,x+1):
    if x%i==0:
      count+=1
  return count==2


In [12]:
print("The primes are : ")
for i in arr1:
  if IsPrime(i):
    print(arr1[i])







The primes are : 
5
10
26


**3. Assending Descending Order of Array**

In [13]:
arr3=np.random.randint(1,100,8)

In [14]:
arr3

array([11,  8, 22, 76, 92, 60, 95,  6])

In [15]:
assending =np.sort(arr3)
assending

array([ 6,  8, 11, 22, 60, 76, 92, 95])

In [16]:
descending=assending[::-1]
descending

array([95, 92, 76, 60, 22, 11,  8,  6])

**4. Reshape of Data**

In [17]:
arr4=np.arange(1,26)
print(arr4)
arr4.size

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]


25

In [18]:
Reshaped=arr4.reshape(5,5)
Reshaped

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

**5.Min Max Values without builtin functions**

In [19]:
arr5=np.random.randint(1,100,10)
arr5

array([53, 97, 79, 69,  3, 57, 69, 60, 27, 18])

In [20]:
_Min=arr5[0]
_Max=arr5[0]
for i in arr5:
  if i<_Min:
    _Min=i
  if i>_Max:
    _Max=i
print(f" The minimum and Maximum in Array are :\n min {_Min}\n max {_Max}")




 The minimum and Maximum in Array are :
 min 3
 max 97


**6.Positions of Min Max Values without argmin argmax **

In [24]:
arr6=np.random.randint(1,100,10)
arr6

array([82, 34, 49, 40, 73, 75, 31, 94, 53, 97])

In [25]:
min_=0
max_=0
for i in range(len(arr6)):
  if arr6[i]<arr6[min_]:
    min_=i
  if arr6[i]>arr6[max_]:
    max_=i

In [26]:
print(f"The position of min max are :\n min's {min_} \n max's {max_} ")

The position of min max are :
 min's 6 
 max's 9 


**7. Palindrome Series using Numpy**

In [27]:
def PalindromeSeries(n):
  return str(n)==str(n)[::-1]

In [28]:
palindromes=np.array([x for x in range(150) if PalindromeSeries(x)])

In [30]:
print("These are palindrome numbers : ",palindromes)

These are palindrome numbers :  [  0   1   2   3   4   5   6   7   8   9  11  22  33  44  55  66  77  88
  99 101 111 121 131 141]


**8. Data set of student without Pandas**

In [39]:
import random

data = []
for _ in range(100):
    row = [
        random.randint(18, 30),           # age
        random.choice(['M', 'F']),        # gender
        random.randint(60, 100),          # marks1
        random.randint(60, 100),          # marks2
        random.randint(60, 100),          # marks3
        random.randint(60, 100),          # marks4
        random.randint(60, 100),          # marks5
        random.choice(['Yes', 'No']),     # sports
        random.choice(['Urban', 'Rural']),# location
        random.choice(['A', 'B', 'C'])     # grade
    ]
    data.append(row)

data_np = np.array(data)
print("Sample row:", data_np[0])


Sample row: ['29' 'F' '99' '68' '90' '95' '60' 'No' 'Rural' 'B']


**9.Variable conversion **

In [40]:
arr = np.array([1, 2, 3, 4])
converted = arr.astype(float)
print("Converted to float:", converted)


Converted to float: [1. 2. 3. 4.]


**10. 10 operations with user defined Function **

In [41]:
def math_operations(a, b):
    print("Add:", a + b)
    print("Subtract:", a - b)
    print("Multiply:", a * b)
    print("Divide:", a / b)
    print("Modulus:", a % b)
    print("Power:", a ** b)
    print("Floor Div:", a // b)
    print("Bitwise AND:", a & b)
    print("Bitwise OR:", a | b)
    print("Bitwise XOR:", a ^ b)

math_operations(10, 3)


Add: 13
Subtract: 7
Multiply: 30
Divide: 3.3333333333333335
Modulus: 1
Power: 1000
Floor Div: 3
Bitwise AND: 2
Bitwise OR: 11
Bitwise XOR: 9


FUNCTION:-

-> The function is a block of reusable code that performs a specific task.

CLASS :-
-> The class is a blueprint for creating objects and Object is Instance of Class
-> Class  encapsulates data and functions together.

Examples:

Function:



def greet("name):

    print("Hello", name)

Class:

class Greeter:
    
    def greet(self,name):
        
        print("Hello",name)
